authenticate/urls.py
from django.conf.urls import url

from . import views

app_name = 'authenticate'

urlpatterns = [
	url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^logout/$', views.logout_user, name='logout'),
]

insta/urls.py
from django.conf.urls import url

from . import views

app_name = 'insta'

urlpatterns = [
    url(r'^page/$', views.GetPage.as_view(), name='get_page'),

    url(r'^post/$', views.GetPostImg.as_view(), name='get_post'),
    url(r'^post/(?P<postid>\d+)/$', views.PostDetail.as_view(), name="post_detail"),
    url(r'^post/(?P<postid>\d+)/delete/$', views.DeletePost.as_view(), name="delete_post"),

    url(r'^savepost/(?P<page>[\w-]+)/(?P<img>.+)/$', views.SaveIgPost.as_view(), name="save_post"),

    url(r'^savedposts/$', views.ViewSaved.as_view(), name="view_saved"),
    url(r'^savedposts/(?P<tag>[\w-]+)/$', views.ViewSavedTag.as_view(), name="save_tag"),

   url(r'^tags/$', views.ManageTags.as_view(), name='manage_tags'),
   url(r'^tags/edit/(?P<tag>\d+)$', views.EditTag.as_view(), name='edit_tag'),
   url(r'^tags/delete/(?P<tag>\d+)$', views.DeleteTag.as_view(), name='delete_tag'),

]

insta_app/urls.py
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url(r'', include('insta.urls')),
    url(r'', include('authenticate.urls')),
    url(r'^admin/', admin.site.urls),

    # url(r'^insta/', include('insta.urls')),
]

insta/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.

class IgPage(models.Model):
    page = models.CharField(max_length=250, null=True)
    url = models.CharField(max_length=2083, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

# class IgPost(models.Model):
# 	url = models.CharField(max_length=2083, null=True)
# 	page = models.CharField(max_length=250, null=True)
# 	img = models.CharField(max_length=2083, null=True)
# 	tag = models.CharField(max_length=250, null=True)
# 	user = models.IntegerField(null=True)

class SavePost(models.Model):
	url = models.CharField(max_length=2083, null=True)
	# post_url = models.CharField(max_length=2083, null=True)
	page = models.CharField(max_length=250, null=True)
	img = models.CharField(max_length=2083, null=True)
	tag = models.CharField(max_length=250, null=True)
	user = models.IntegerField(null=True)

class Tags(models.Model):
	tag = models.CharField(max_length=250, null=True)
	user = models.IntegerField(null=True)

insta/forms.py
from django import forms
import utils

# TAGS = [
# ('cars', 'Cars'),
# ('inspiration', 'Inspiration'),
# ('other', 'Other'),
# ]

# TAGS = utils.tag_dropdown(1)

class PostForm(forms.Form):
	post = forms.CharField(label='IG Post URL', max_length=250)
	# tag = forms.CharField(label='Tag:', 
	# 					  widget=forms.Select(choices=TAGS))

class PageForm(forms.Form):
	page = forms.CharField(label='IG Page Name', max_length=150)


class TagForm(forms.Form):

	TAGS = utils.tag_dropdown(2)

	print TAGS

	tag = forms.CharField(label='Tag:', 
						  widget=forms.Select(choices=TAGS), 
						  required=False,
						  )

	new_tag = forms.CharField(label='Tag name:', max_length=250)

	def __init__(self, *args, **kwargs):
		self.user = kwargs.pop('user',None)
		super(TagForm, self).__init__(*args, **kwargs)
		self.fields['tag'] = forms.CharField(label='Tag:', 
							  widget=forms.Select(choices=utils.tag_dropdown(self.user)), 
							  required=False,
							  )

	# def tag_fields(self):

	# 	userid = self.user

	# 	TAGS = utils.tag_dropdown(userid)

	# 	print TAGS

	# 	tag = forms.CharField(label='Tag:', 
	# 						  widget=forms.Select(choices=TAGS), 
	# 						  required=False,
	# 						  )

	# 	new_tag = forms.CharField(label='Tag name:', max_length=250)


		

		
		# self.fields['user_id'].initial = self.user

		# self.TAGS = utils.tag_dropdown(self.user)
		

insta/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from .models import IgPage, SavePost, Tags
from .forms import PostForm, PageForm, TagForm

import utils


def index(request):
	
	return render(request, 'index.html', {})


class GetPostImg(LoginRequiredMixin, View):

	def get(self, request):

		userid = request.user.pk

		form = PostForm()
		savedposts = SavePost.objects.filter(user=userid).order_by('-id')[:5]

		context = {
			'form': form,
			'page': "None",
			'post': "None",
			'recent': savedposts
		}

		return render(request, 'post.html', context)

	def post(self, request):

		userid = request.user.pk
		
		form = PostForm(request.POST)
		response = None

		if form.is_valid():

			response = form.cleaned_data['post']

			# imgscript = utils.get_post_script(response, 4)
			# imgurl = utils.get_post_src(imgscript) 
			imgurl = utils.get_post_script(response, 3, "postscript")

			## temporary commenting this out:
			# pagescript = utils.get_post_script(response, 4)
			# pagename = utils.get_page_from_post(pagescript, 3)
			pagename = utils.get_post_script(response, 2, "pagescript")
			# pagename = "test"

			context = {
				'form': form,
				'page': pagename,
				'post': imgurl,
				'recent': ""
			}

			return render(request, 'post.html', context)


class GetPage(LoginRequiredMixin, View):

	def get(self, request):

		form = PageForm(request.GET)
		user = request.user
		
		if form.is_valid():
			
			page = form.cleaned_data['page']
			url = utils.get_page_url(page)

			request.session['page'] = page 

			igpage = IgPage(page=page, url=url, user=user)
			igpage.save()

			allpages = IgPage.objects.filter(user=user)

			allimgs = utils.get_page_script(url)
			# print allimgs

			context = {
				'form': form,
				'page': page,
				'pageurl': url,
				'posts': allimgs,
				'allpages': allpages
			}

			return render(request, 'page.html', context)

		else: 
			form = PageForm()
			allpages = IgPage.objects.filter(user=user).order_by('-id')[:5]
			context = {
				'form': form,
				'page': "None",
				'pageurl': "",
				'posts': [],
				'allpages': allpages,
			}

			return render(request, 'page.html' , context)


class SaveIgPost(View):

	def get(self, request, **kwargs):

		userid = request.user.pk
		igpage = kwargs.get('page')
		imgurl = kwargs.get('img')
		pageurl = "https://www.instagram.com/%s" % igpage

		# print "this is the img: %s and this the page: %s" % (imgurl, igpage)

		# Save to DB:
		saveigpost = SavePost(url=pageurl, page=igpage, img=imgurl, user=userid)
		saveigpost.save()

		pagecontent = "Img saved! %s %s" % (igpage, imgurl)

		# return HttpResponse(pagecontent)

		# redirecturl = '/page/?page=%s' % igpage
		previousurl = request.META['HTTP_REFERER']

		messages.success(request, ('Post was saved!'))

		return redirect(previousurl)


class ViewSaved(LoginRequiredMixin, View):

	def get(self, request):

		userid = request.user.pk
		savedposts = SavePost.objects.filter(user=userid).order_by('-id')
		tags = savedposts.values('tag').distinct().exclude(tag=None)

		context = {
			'posts': savedposts,
			'tags': tags
		}

		return render(request, 'saved_posts.html', context)


class PostDetail(LoginRequiredMixin, View):

	def get(self, request, postid):

		userid = request.user.pk
		post = SavePost.objects.get(pk=postid)
		# tags = Tags.objects.filter(user=userid)

		# utils.tag_dropdown(1)

		next_post = post.id + 1
		previous_post = post.id - 1

		form = TagForm(user=userid)

		context = {
			'form': form, 
			'post': post,
			'next': next_post,
			'previous': previous_post,
			'tag': post.tag
		}

		if userid == post.user:
			return render(request, 'post_detail.html', context)
		else:
			return redirect('insta:view_saved')

	def post(self, request, postid):

		form = TagForm(user=request.user.id)

		if form.is_valid():
			
			tag = form.cleaned_data['tag']

			post = SavePost.objects.get(pk=postid)
			next_post = post.id + 1
			previous_post = post.id - 1

			unique_tags = SavePost.objects.filter(tag=tag)

			post.tag = tag
			post.save()

			context = {
				'form': form,
				'post': post,
				'next': next_post,
				'previous': previous_post,
				'tag': post.tag
			}

			return render(request, 'post_detail.html', context)


class DeletePost(View):

	def get(self, request, postid):

		post = SavePost.objects.get(pk=postid)
		post.delete()

		return redirect('/savedposts/')


class ViewSavedTag(View):
	## page to see post with a certain tag only
	def get(self, request, tag):
		
		tagged_posts = SavePost.objects.filter(tag=tag)
		all_tags = SavePost.objects.all().values('tag').distinct().exclude(tag=None)


		context = {
			'posts': tagged_posts,
			'tags': all_tags,
		}

		return render(request, 'saved_posts.html', context)


class ManageTags(LoginRequiredMixin, View):

	def get(self, request):

		userid = request.user.id

		all_tags = Tags.objects.filter(user=userid).distinct().exclude(tag=None)
		# all_tags = SavePost.objects.all().values('tag').distinct().exclude(tag=None)

		form = TagForm(user=userid)

		context = {
			'tags': all_tags,
			'form': form,
		}

		return render(request, 'manage_tags.html', context)

	def post(self, request):

		userid = request.user.id
		all_tags = Tags.objects.filter(user=userid).distinct().exclude(tag=None)
		# all_tags = SavePost.objects.all().values('tag').distinct().exclude(tag=None)

		form = TagForm(request.POST)
		userid = request.user.pk
		# tag_name = form.cleaned_data['tag_name']

		if form.is_valid():
			tag_name = form.cleaned_data['new_tag']
			save_tag = Tags(tag=tag_name, user=userid)
			save_tag.save()

			context = {
				'tags': all_tags,
				'form': form,
			}

			return render(request, 'manage_tags.html', context)


class EditTag(LoginRequiredMixin, View):

	def get(self, request, tag):

		userid = request.user.id

		all_tags = Tags.objects.filter(user=userid).distinct().exclude(tag=None)
		current_tag = Tags.objects.filter(pk=tag)

		form = TagForm(user=userid)

		context = {
			'tags': all_tags,
			'current_tag': current_tag,
			'form': form,
		}

		return render(request, 'edit_tag.html', context)

	def post(self, request, tag):

		userid = request.user.id

		form = TagForm(request.POST)

		if form.is_valid():

			all_tags = Tags.objects.filter(user=userid).distinct().exclude(tag=None)
			tag_name = form.cleaned_data['new_tag']
			current_tag = Tags.objects.filter(pk=tag)
			current_tag.update(tag=tag_name)

			context = {
				'tags': all_tags,
				'current_tag': current_tag,
				'form': form,
			}
			try:
				messages.success(request, ('Tag was successfully changed'))
				return render(request, 'manage_tags.html', context)
			
			except:
				messages.success(request, ('Something went wrong...'))
				return render(request, 'edit_tag.html', context)


class DeleteTag(View):

	def get(self, request, tag):

		tag = Tags.objects.get(pk=tag)
		tag.delete()
		messages.success(request, ('Tag was successfully deleted'))

		return redirect('/tags/')

		



	# Further development:
	# + after entering page, you see the first 10 posts, and you can tag and save to the database
	# + after entering post url, you can save the post to database
	# + page with all saved post
	# + logic to delete post on detail page
	# + posts page should have all saved posts with filters by tag
	# + post detail page, you can see full size and change tag here
	# + manage tag page (create, delete or rename tags)
	# + page view: scroll and grid view
	# - page view: sort by page
	# - rename variables with underscore in naming (correct python naming)
	# - add original post url to model/db


	# Bug:
	# + Underscores or periods in page names
	# + Some posts don't load
	# - Previous and next buttons on Saved Post detail page
	# - tags with spaces don't work on savedposts page

insta/templates/insta/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.1.1.min.js"></script>

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'insta/style.css' %}">

    <title>{% block title %}My amazing site{% endblock %}</title>

</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <a class="navbar-brand ml-4" href="#">Appname</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'authenticate:index' %}">Home <span class="sr-only">(current)</span></a>
              </li>
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'insta:get_post' %}">Post</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'insta:get_page' %}">Page</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'insta:view_saved' %}">Saved Posts</a>
              </li>
             <li class="nav-item">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'insta:manage_tags' %}">Tags</a>
              </li>
            </ul>
             <ul class="navbar-nav ml-auto">
              <li>
                <a class="nav-link" href="{% url 'authenticate:logout' %}">Logout</a>
              </li>
            </ul>
            {% else %}
            </ul>
            <ul class="navbar-nav ml-auto">
             <li class="nav-item">
                <a class="nav-link" href="{% url 'authenticate:login' %}">Login</a>
              </li>
            </ul>
            {% endif %}
          </div>
        </div>
    </nav>

    {% if messages %}
    <div class="container">
        <div class="col-md-12">
            {% for message in messages %}
            <div class="alert alert-warning alert-dismissable" role="alert">
                <button class="close" data-dismiss="alert">
                    <small><sup>x</sup></small>
                </button>
                {{ message }}
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
</body>
</html>

insta/templates/insta/edit_tag.html
{% extends "base.html" %}

{% block title %}My amazing blog{% endblock %}


{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-5">
			<h1 class="mb-3">Tags</h1>
			<ul class="list-group">
			{% for tag in tags %}
			<li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
				{{ tag.tag }} 
				<a href="{% url 'insta:edit_tag' tag=tag.id %}"><span class="badge badge-light badge-pill">edit</span></a>
			</li>
			{% endfor %}
			</ul>

		</div>

		{% for current in current_tag%}
		<div class="col-md-6">
			<h4 class="mt-4 mb-3">Edit: {{ current.tag }}</h4>

			<form action="{% url 'insta:edit_tag' tag=current.id %}" method="POST">
				<div class="form-group">
					<label for="" class="">New tagname:</label>
					{{ form.new_tag }}
				</div>
				<a href="{% url 'insta:delete_tag' tag=current.id %}">
					<button type="button" class="btn btn-danger">Delete</button>
				</a>
				<button type="submit" class="btn btn-primary">Save</button>
				{% csrf_token %}
			</form>
		</div>
		{% endfor %}
	</div>
</div>

{% endblock %}

insta/templates/insta/index.html
{% extends "base.html" %}

{% block title %}Insta Index{% endblock %}


{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-6">
			<h1>Index</h1>
			<p>Welcome to the index</p>
			{{ test1 }}
			{{ test2 }}
		</div>
	</div>
</div>

{% endblock %}

insta/templates/insta/manage_tags.html
{% extends "base.html" %}

{% block title %}My amazing blog{% endblock %}


{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-5">
			<h1 class="mb-4">Tags</h1>

			<ul class="list-group">
			{% for tag in tags %}
			<li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
				{{ tag.tag }} 
				<a href="{% url 'insta:edit_tag' tag=tag.id %}"><span class="badge badge-light badge-pill">edit</span></a>
			</li>
			{% endfor %}
			</ul>

		</div>

		<div class="col-md-6">
			<h4 class="mt-4 mb-3">Add new tag:</h4>

			<form action="{% url 'insta:manage_tags' %}" method="POST">
				<div class="form-group">
					<label for="" class="">Tag:</label>
					{{ form.new_tag }}
				</div>
				<button type="submit" class="btn btn-primary mb-2">Save</button>
				{% csrf_token %}
			</form>
		</div>
	</div>
</div>

{% endblock %}

insta/templates/insta/page.html
{% extends "base.html" %}

{% block title %}My amazing blog{% endblock %}


{% block content %}


<div class="container">

	<div class="col-md-6">
		<h1 class="mb-4">Page</h1>
		<form action="{% url 'insta:get_page' %}" method="GET">
			<div class="form-group">
				<p>Enter page name:</p>
				<label for="" class="">Page:</label>
				{{ form.page }}
			</div>
			<button type="submit" class="btn btn-primary mb-2">Submit</button>
			<!-- {% csrf_token %} NOT NEEDED FOR GET REQUEST -->
		</form>
	</div>

	<div class="col-md-6">
		<br />
		<a href="{{ pageurl }}" target="_blank">{{ pageurl }}</a>
		<br />
	</div>

	{% if "None" in page %}
	<div class="col-md-6">
		5 recent pages:
		<ul>
			{% for ig in allpages %}
			<li><a href="{% url 'insta:get_page' %}?page={{ ig.page }}">{{ ig.page }}</a></li>
			{% endfor %}
		</ul>
	</div>
	{% endif %}

	<div class="row" style="margin-left:0px;">
<!-- 		<div class="col-md-12"> -->
		{% for post in posts %}
			<div class="col-md-4">
				<form action="{% url 'insta:get_page' %}" method="POST">
					<img src="{{ post }}" class="img-fluid">
					<a href="{% url 'insta:save_post' page=page img=post %}">
						<button type="button" class="btn btn-light" id="savepost">Save</button>
					</a>
				</form>
			</div>
<!-- 		</div> -->


	<!-- 	<div id="result">
		</div> -->

	<!-- 	<script>
		$("#savepost").click(function(){ 
		     $.ajax({
		        url: "{% url 'insta:save_post' page=page img=post %}", 
		        success:   function(result){ 
		            console.log(url);
		        }
		      });
		});
		</script> -->

	<!-- 	<script>
			$("#savepost").on('click',function(e) {
			   e.preventDefault();
			  //here you can load verify.aspx by using console.log("saved post");
			  var url = "{% url 'insta:save_post' page=page img=post %}"
			  // console.log(url); 
			   $("#result").load(url); 
			    console.log("saved post");  
			});
		</script> -->

	{% endfor %}
	</div>

</div><!-- ends container -->

{% endblock %}

insta/templates/insta/post.html
{% extends "base.html" %}

{% block title %}My amazing blog{% endblock %}


{% block content %}


<div class="container">
	<div class="col-md-6">
		<h1 class="mb-4">Post</h1>
		<form action="{% url 'insta:get_post' %}" method="POST">
			<div class="form-group">
				<p>Enter post url:</p>
				<label for="" class="">Post:</label>
				{{ form.post }}
				<!-- {{ form.tag }} -->
			</div>
			<button type="submit" class="btn btn-primary mb-2">Submit</button>
			{% csrf_token %}
		</form>
	</div>


{% if "None" not in post %}
	<div class="row">
		<div class="col-md-6">
			<div id="result"></div>
			<img src="{{ post }}" class="img-fluid">
			<a href="{% url 'insta:save_post' page=page img=post %}">
				<button type="button" class="btn btn-light" id="savepost">Save</button>
			</a>
		</div>
	</div>
	{% else %}


	<div class="col-md-6">
		5 recent posts:
	</div>

	<div class="row" style="margin-left:0px;">
		{% for ig in recent %}
		<div class="col-md-3 mb-4">
			<a href="{% url 'insta:post_detail' postid=ig.id %}">
				<img src="{{ ig.img }}" class="img-fluid">
			</a>
		</div>
		{% endfor %}
	</div>

{% endif %}
</div><!-- ends container -->

{% endblock %}

insta/templates/insta/post_detail.html
{% extends "base.html" %}

{% block title %}My amazing blog{% endblock %}


{% block content %}


<div class="container">

	<div class="row">
		<div class="col-12 prevnext">
			<h5><a href="{% url 'insta:post_detail' previous %}" class="badge badge-light">Previous</a></h5>
			<h5><a href="{% url 'insta:post_detail' next  %}" class="badge badge-light">Next</a></h5>
		</div>
	</div>

	<div class="row">
		<div class="col-md-6">
			{% if tag is not None %}
			<h5><span class="badge badge-light">{{ tag }}</span></h5>
			{% endif %}
		</div>
	</div>

	<div class="row justify-content-start">
		<div class="col-12">
			<img src="{{ post.img }}" class="img-fluid">
		</div>
	</div>

	<div class="row">
		<div class="col-md-6">
			<h5><a href="{% url 'insta:get_page' %}?page={{ post.page }}" class="badge badge-info">{{ post.page }}</a></h5>
		</div>
	</div>

	<a href="{% url 'insta:delete_post' postid=post.pk %}" class="btn btn-secondary mb-2">Delete</a>
	<form action="{% url 'insta:post_detail' postid=post.pk %}" method="POST">
		<div class="form-group">
			<label for="" class="">Tag:</label>
			{{ form.tag }}
		</div>
		<button type="submit" class="btn btn-primary mb-2">Save</button>
		{% csrf_token %}
	</form>

</div>

{% endblock %}

insta/templates/insta/saved_posts.html
{% extends "base.html" %}

{% block title %}My amazing blog{% endblock %}


{% block content %}

<div class="container">

	<div class="row mb-2">
		<div class="col-md-10">
			<h1>Saved Posts</h1>
		</div>



		<div class="col-md-2 mt-4">
			<a href="#" class="text-secondary gridlayout">Grid</a>
			<a href="#" class="text-secondary scrolllayout">Scroll</a>
		</div>
	</div>

	<div class="row mb-4">
		<div class="col-md-12">
		{% for tag in tags %}
			<a href="{% url 'insta:save_tag' tag=tag.tag %}">
			<h5><span class="badge badge-secondary">{{ tag.tag|title }}</span></h5>
			</a>
		{% endfor %}
			<a href="{% url 'insta:view_saved' %}">
			<h5><span class="badge badge-secondary">All</span></h5>
			</a>
		</div>
	</div>

	<div class="row">

	{% for post in posts %}
	<div class="mb-4 overview">
		<a href="{% url 'insta:post_detail' post.pk  %}">
			<img src="{{ post.img }}" class="post img-fluid">
		</a>
	</div>
  {% endfor %}

	<!-- {% for post in posts %}
		{% if request.GET.view %}
		<div class="col-sm-12 mb-4 overview">
		{% else %}
		<div class="col-sm-4 mb-4 overview">
		{% endif %}
			<a href="{% url 'insta:post_detail' post.pk  %}">
				<img src="{{ post.img }}" class="img-fluid">
			</a>
		</div>
	{% endfor %} -->
	</div> <!-- ends row -->

</div> <!-- ends container -->

<script>
	$('.gridlayout').click(function(){
		$('.overview').addClass('col-sm-4');
		$('.overview').removeClass('col-sm-12');
	});

	$('.scrolllayout').click(function(){
		$('.overview').addClass('col-sm-12');
		$('.overview').removeClass('col-sm-4');
	});
</script>

{% endblock %}